Source/Data/k8s/Development/configmap.yml

Adding the environment variable to the configmaps, to be closer to the Operations setup.

add environment

---

.github/workflows/deploy-ms.yml
Source/Data/k8s/Development/configmap.yml

Fix deploy script to point ot v3 cluster

---

Source/Portal/Web/layouts/AppHeader.tsx

- Able to change tenant
- Confirming CI / CD pipeline.

Adding a link to change tenant

---

Source/Portal/Web/layouts/AppHeader.tsx

Wanting to trigger a build after #59 and #58

Removing unused variable

---

Source/Data/Web/App.tsx

Production take 2

---

Source/Data/Backend/backups/api.ts
Source/Data/Backend/environment.ts
Source/Data/k8s/Development/configmap.yml
Source/Data/k8s/Production/configmap.yml

- Only fixing "Data" as I can't quite get the lay of the land, yet.
- Development got out of sync, my fault as I am learning to keep the configmap in here.
- Moving x-secret to be configured via ENV.

Updating configmaps to use __

---

Source/Applications/microservice.json
Source/Data/Backend/backups/api.ts
Source/Data/Backend/environment.ts
Source/Data/Backend/index.ts
Source/Data/Web/App.tsx
Source/Data/k8s/Development/configmap.yml
Source/Data/k8s/Production/configmap.yml
Source/Data/microservice.json

Same as #65 but with label to trigger rebuild.

Trigger build actions

---

Source/SelfService/Backend/main.go
Source/SelfService/Web/api.ts
Source/SelfService/Web/application/info.tsx
Source/SelfService/Web/micoservice/Microservice.tsx
Source/SelfService/Web/micoservice/StaticSite.tsx
Source/SelfService/Web/micoservice/businessMomentsAdaptor/BusinessMomentsAdaptor.tsx
Source/SelfService/Web/micoservice/podStatus.tsx
Source/SelfService/Web/micoservice/viewCard.tsx
Source/SelfService/Web/screens/applicationOverviewScreen.tsx
Source/SelfService/Web/screens/applicationScreen.tsx
Source/SelfService/Web/screens/backupScreen.tsx
Source/SelfService/Web/screens/microserviceViewScreen.tsx
Source/SelfService/Web/screens/todoScreen.tsx

- Fix creating business moments via ui
- Make delete work

Post buisness moments

---

Source/SelfService/Web/backup/viewCard.tsx
Source/SelfService/Web/micoservice/viewCard.tsx
Source/SelfService/Web/screens/applicationScreen.tsx
Source/SelfService/Web/screens/backupScreen.tsx
Source/SelfService/Web/theme/viewCard.ts

I really wanted to get the figma background for cards.
https://www.figma.com/file/OPDbO214o4LjpTu316WyMf/Studio-Mockups?node-id=162%3A2383

Butchering the themes to work

---

Source/SelfService/Web/microservice/microservice.scss
Source/SelfService/Web/microservice/viewCard.tsx
Source/SelfService/Web/screens/applicationOverviewScreen.tsx
Source/SelfService/Web/stores/microservice.ts

- Click card takes to microservice overview
- Starting to bring the View Card to life based on the figma designs.
- https://www.figma.com/file/OPDbO214o4LjpTu316WyMf/Studio-Mockups?node-id=469%3A1096
- https://app.asana.com/0/1200403658239260/1200384263317575/f

Bug click card 1

---

Source/BusinessMomentsAdaptorImage/docker-compose.yml
Source/BusinessMomentsAdaptorImage/index.ts
Source/BusinessMomentsAdaptorImage/server.ts
Source/BusinessMomentsAdaptorImage/tsconfig.json
Source/BusinessMomentsAdaptorImage/webhookReceived.ts
Source/BusinessMomentsAdaptorImage/wehbookReceivedHandler.ts

PR for adding SDK and runtime config to Business Moments Adaptor.
Solvs https://app.asana.com/0/1200403658239260/1200358538105062/f

Adding SDK and runtime config to Business Moments Adaptor

---

Source/SelfService/Web/api/backups.ts
Source/SelfService/Web/backup/listView.tsx
Source/SelfService/Web/backup/viewCard.tsx

Linked with https://github.com/dolittle-entropy/platform-api/pull/13.

Making Studio inline with the api coming into play

---

Source/SelfService/Docs/deployment.md
Source/SelfService/Web/Dockerfile

Fix the Dockerfile for SelfService Web
- The Dockerfile for SelfService Web

Fix SelfService Web Dockerfile

---

.editorconfig
Makefile
Source/SelfService/BackendMock/controllers/applications/ApplicationController.ts
Source/SelfService/BackendMock/controllers/applications/given.ts
Source/SelfService/BackendMock/controllers/liveApplications/given.ts

Change the mock data to all be from the same application and tenant
https://app.asana.com/0/1200879032451150/1200913011763257/f

Add correct mock data

---

Documentation/k3d.md
Makefile

Improving the documentation around using local-dev

Improving the docs after Joel

---

Environment/k3d/git/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/11b6cf47-5d9f-438f-8116-0d9828654657/application.json

Updated the k3d local dev sample data to correspond to the changes in https://github.com/dolittle/platform-api/pull/19

Update platform-api sample data

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/Microservice.tsx
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/purchaseOrder/create.tsx
Source/SelfService/Web/microservice/purchaseOrder/overview.tsx
Source/SelfService/Web/microservice/viewCard.tsx
Source/SelfService/Web/stores/microservice.ts

- Based on the ingress changes from earlier in the week
- It brings back the base microservice as well (as a by-product)

Bringing the new ingress to life

---

Source/SelfService/Web/webpack.config.ts

Error in the image url.
https://app.asana.com/0/1200899594200551/1201018124798215/f

WIP: Issue with images via docker image

---

Source/SelfService/Web/api/cicd.ts
Source/SelfService/Web/documentation/cicd/setupAzurePipelines.tsx
Source/SelfService/Web/documentation/container.tsx
Source/SelfService/Web/package.json
Source/SelfService/Web/screens/applicationsScreen.tsx

- Able  to download service account credentials, making it easier to setup azure pipeline.
- Able to download container registery, making it easier to setup azure pipeline.

Buttons to download credentials

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/base/view.tsx
Source/SelfService/Web/microservice/businessMomentsAdaptor/view.tsx
Source/SelfService/Web/microservice/purchaseOrder/view.tsx
Source/SelfService/Web/microservice/rawDataLog/view.tsx
Source/SelfService/Web/microservice/view/healthStatus.tsx

- A button to restart the microservice.

A button to restart the microservice

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/environmentVariables/view.tsx
Source/SelfService/Web/screens/microservicesScreen.tsx

- View current environment variables for a microservice
- Update microservice environment variables

Simple env variable config

---

Source/SelfService/Web/microservice/base/view.tsx

Link from config page

---

Source/SelfService/Web/microservice/base/view.tsx

Nothing to see, just triggering labels.

Trigger build

---

Source/SelfService/Web/microservice/create.tsx

- Disable creation of microservice, whilst we fix a few bugs

Disabling creation of microservice

---

Makefile
Source/SelfService/Web/documentation/accessContainerRegistry.tsx
Source/SelfService/Web/documentation/cicd/setupAzurePipelines.tsx
Source/SelfService/Web/documentation/container.tsx
Source/SelfService/Web/documentation/verifyKubernetesAccess.tsx
Source/SelfService/Web/stores/documentationInfo.ts

- Adding typing to the data coming via personalised-info endpoint.
- Able to override the DOLITTLE_CUSTOMER_ID via `make develop-backend`.

Being specific about information from the backend

---

Source/SelfService/Web/documentation/container.tsx
Source/SelfService/Web/documentation/verifyKubernetesAccess.tsx
Source/SelfService/Web/stores/documentationInfo.ts

Via [Documentation /Verify access to kubernetes it bubbles up some helper commands

Showing some commands a user has access to

---

Source/SelfService/Web/businessMoments/overview.tsx
Source/SelfService/Web/microservice/base/view.tsx
Source/SelfService/Web/microservice/businessMomentsAdaptor/view.tsx
Source/SelfService/Web/microservice/delete.tsx
Source/SelfService/Web/microservice/overview.tsx
Source/SelfService/Web/microservice/purchaseOrder/view.tsx
Source/SelfService/Web/microservice/rawDataLog/view.tsx
Source/SelfService/Web/microservice/view.tsx
Source/SelfService/Web/microservice/viewCard.tsx
Source/SelfService/Web/screens/microservicesScreen.tsx
Source/SelfService/Web/stores/microservice.ts

- Making the delete button for a microservice work via viewcard.
- Making the delete button for a microservice work via microservice view.
- Delete screen, to warn the action today is permanent.

Make delete work

---

Documentation/Development/feature-application-namespace.md
Documentation/k3d.md
Environment/k3d/git/Source/V3/platform-api/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/11b6cf47-5d9f-438f-8116-0d9828654657/application.json
Makefile
Source/SelfService/Backend/README.md
Source/SelfService/Backend/main.go
Source/SelfService/Docs/development.md
Source/SelfService/Web/App.tsx
Source/SelfService/Web/api/application.ts
Source/SelfService/Web/api/backups.ts
Source/SelfService/Web/api/index.ts
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/base/view.tsx
Source/SelfService/Web/microservice/businessMomentsAdaptor/create.tsx
Source/SelfService/Web/microservice/microserviceEditScreen.tsx
Source/SelfService/Web/microservice/purchaseOrder/create.tsx
Source/SelfService/Web/microservice/staticSite/create.tsx

- Fixing the http contract for tenantId -> customerId and tenantName -> customerName.
- Renaming to use DEVELOPMENT_CUSTOMER_ID and DEVELOPMENT_USER_ID

Make Studio happy with changes from the backend

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/base/create.tsx

- Adding 6.1.0 to the runtime list for create microservice
- Moving to 7.8.0 for the latest runtime

More runtimes

---

Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/studio.json

Was not able to create new application and envs locally.

Enabled can_create_application for local dev env

---

README.md

Adds CodeClimate badges so that's its easier to navigate to the CodeClimate pages.

Add CodeClimate badges for easier access to it and to track progress

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/api/index.ts
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/base/view.tsx
Source/SelfService/Web/stores/microservice.ts
Source/SelfService/Web/theme/dropDownMenu.tsx
Source/SelfService/Web/theme/switch.tsx
Source/SelfService/Web/theme/textField.tsx

This PR will 
- Introduce a toggle to allow the user to specify if they want to create a private or public microservice. This is set to private by default.
- Bump latest selectable runtime version to 7.8.1
- Contains the contents of https://github.com/dolittle/Studio/pull/165
https://app.asana.com/0/1202023614957161/1202039820012594/f
https://github.com/dolittle/platform-api/pull/105
https://app.asana.com/0/1201955720774352/1201993650094128/f
https://github.com/dolittle/platform-api/pull/102

Create private microservice UI

---

Environment/k3d/git/Source/V3/platform-api/dev/453e04a7-4f9d-42f2-b36c-d51fa2c83fa3/customer.json
Environment/k3d/k8s/api-v1.yml

In the local cluster, the "local-dev" user now has access to view the admin screens.

Making admin work in the local cluster

---

Source/SelfService/Web/package.json
Source/Shared/Web/package.json
package.json
yarn.lock

Manually set the resolution for `@types/react` to version 17.0.39, as this was being resolved to 18.0.1 that is not compatible with @material-ui/core@4.x

resolutions are not working, or i am failing to use them correctly :P

---

Source/SelfService/Web/admin/application/view.tsx
Source/SelfService/Web/api/application.ts
Source/SelfService/Web/api/customer.ts
Source/SelfService/Web/api/studio.ts
Source/SelfService/Web/customer/view.tsx
Source/SelfService/Web/screens/adminScreen.tsx

- Application view access screen, with add + remove
- Link page to take you to the customers from the admin screen

Admin view to list / add / remove users from an application

---

Environment/k3d/reset-local-k3d

The k8s files weren't being applied as the command was running in the wrong directory.

Fix the `reset-local-k3d` command

---

Source/SelfService/Web/api/application.ts
Source/SelfService/Web/api/index.ts
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/base/view.tsx

- Via microservice creation, if m3connector connection is enabled, give the user the option to connect m3connector for this microservice

Bringing connections to the application

---

Source/SelfService/Backend/go.mod
Source/SelfService/Backend/go.sum

Fixes make develop-backend
Remember to remove sections that you don't need or use.
- added x/sys to sum and mod files for Selfervice Backend

addd x/sys to sum and mod files for Selfervice Backend

---

Source/SelfService/Web/customer/view.tsx

- Fixed bug in customer screen within admin where view access would be repeated for each environment

Unique applications with their environments

---

Source/SelfService/Web/CHANGELOG.md

fix changelog for mounting files

---

Source/SelfService/Web/api/m3connector.ts

Previous PR that was merged to main didn't trigger.

Change to trigger build

---

Source/SelfService/Web/m3connector/details.tsx

Via m3connector screen, clicking on the links will reveal the contents

m3connector details screen on click, reveal the contents

---

Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx

- Fixes crashing app when manually entering invalid date in logs date-range filter

Fix-edit-date-range-crash-app

---

Source/SelfService/Web/logging/logFilter/logFilterToLabelsAndPipeline.ts
Source/SelfService/Web/logging/logFilter/searchFilter.tsx

- Search filter placeholder text style changed to italic
- Updated search to be case insensitive

Make search case-insensitive and update placeholder text style

---

Source/SelfService/Web/application/create/create.tsx
Source/SelfService/Web/application/create/createFormActionButtons.tsx
Source/SelfService/Web/screens/applicationsScreen.tsx
Source/SelfService/Web/utils/formTextFieldsValidation.ts

Made application buttons to be as wide as the longest button is.
Fixed error message on 'application name' field for not giving error when name is only one char long because it is not what error message would suggest.
Removed underline styling from 'select new customer' link.
- Application selection buttons width
- Text field error handling
- Link appearance on Safary and Chrome
- Unnecessary punctuations

Login flow fixes

---

Source/SelfService/Web/microservice/environmentVariables/view.tsx

- Removes forced capitalization of variable names
- Lets the input fields fill the column space, giving more space to view the content

Usability improvements for environment variables page

---

Source/SelfService/Web/microservice/dataTable.tsx

This PR will fix errors with microservices overview data table, when data is undefined.
- Refactored customUrlFieldSort function
- Microservices data table errors

Fix data table

---

Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx
Source/SelfService/Web/logging/logFilter/filterSelect.tsx
Source/SelfService/Web/screens/logsScreen.tsx

Fixed menu dropdown styles when hovered and added padding.
- Menu items hover and focused state style

Fixed menu item styles

---

Source/SelfService/Web/microservice/environmentVariables/view.tsx

Shows the environment variables alphabetically on load in the edit page

Ordered environment variables in edit page

---

Source/SelfService/Web/microservice/dataTable.tsx

Capitalized first letter in data table runtime version column.
- Capitalized first letter in runtime version

Capitalize first letter in runtime vs

---

Source/SelfService/Web/microservice/dataTable.tsx

Guards against missing runtime version in microservices page

Prevent exceptions if runtimeVersion is not found

---

Source/SelfService/Web/App.tsx
Source/SelfService/Web/insights/container.tsx
Source/SelfService/Web/insights/dumpJson.tsx
Source/SelfService/Web/insights/runtimeStatsV1/failingPartitionsSummary.tsx
Source/SelfService/Web/insights/runtimeStatsV1/runtimeV1Stats.tsx
Source/SelfService/Web/insights/runtimeStatsV1/stateSummary.tsx
Source/SelfService/Web/insights/runtimeStatsV1/utils.ts
Source/SelfService/Web/layout/layoutWithSidebar.tsx
Source/SelfService/Web/screens/insightsScreen.tsx

Commented out all code related to 'Insight' page doe need for needing improvements (access the db directly instead of using APIs) etc.
- Hided Insight menu item and its content.

Remove insight menu item

---

Source/SelfService/Web/theme/theme.ts

Updated Theme colors.
- Theme colors

Theme colors updated

---

Source/SelfService/Web/theme/theme.ts

Theme font weights was outdated and needed update.
- Updated theme font weights and divider opacity.

Updated theme

---

Source/DesignSystem/atoms/Forms/Form.tsx
Source/DesignSystem/atoms/Forms/Input.tsx
Source/DesignSystem/atoms/Forms/helpers.ts
Source/SelfService/Web/application/create/create.tsx

Smaller 'Create new appliaction' page fixes.
- Loading state while application is created.
- Remove form active field error when user starts to typing again previosly errored field.
- Styling improvements.

Create app errors styling fix

---

Source/DesignSystem/atoms/Button/Button.tsx
Source/SelfService/Web/application/create/create.tsx
Source/SelfService/Web/screens/applicationsScreen/applicationsList.tsx

Fixed error that accoured after Creating New Application - React needs uniq keys for every list item whitch we did not have.
Also removed console.log that should not be in production.
Fixed some styling that they would be more uniformed.
Used Buttons from Storybook instead imports from MUI.
- Each list items in Applications page has now uniq key that React needs
- MUI imported Button to Button from Storybook
- Made styles more uniform
- console.log after new application was created

Create application fixes

---

Source/SelfService/Web/microservice/microserviceView/microserviceView.tsx

Fix for errors that appeared after merge and wrongly solved conflicts in MicroserviceView.tsx.
- Removed double code

Removed double code

---

Source/SelfService/Web/microservice/dataTable.tsx
Source/SelfService/Web/microservice/microserviceView/configuration/configuration.tsx
Source/SelfService/Web/microservice/microserviceView/configuration/setupSection.tsx
Source/SelfService/Web/microservice/microserviceView/helpers.ts

This PR will fix error that occurred when Microservice object is not containing 'extra' object and when configuration files fetch failes.
Also added few helper functions that capitalize string and removes unwanted part from string.
- Helper functions for capitalization and cleaning string.
- Error on 'Configuration Files' failed fetch
- Error if Microservice object does not contain 'extra' object.

Configuration header fixes

---

.github/workflows/deploy-bridge-frontend.yml
Source/Bridge/bridge-frontend/pages/index.tsx

Move the deployment job out of the reusable workflow and straight into bridge deploy workflow

Fix deployment credentials

---

.github/workflows/deploy-bridge-frontend.yml
Source/Bridge/bridge-frontend/pages/index.tsx

Fix the build. Really. I mean it! Added the head container as the one to be patched

Fix deployment image

---

Source/DesignSystem/atoms/Button/Button.stories.tsx

Add description to button component.

Add description to button component

---

Source/DesignSystem/atoms/Button/Button.stories.tsx
Source/DesignSystem/atoms/ConfirmDialog/ConfirmDialog.stories.tsx

Added description to button component and confirm dialog component.

Added descriptions to multiple components

---

Source/DesignSystem/atoms/Button/Button.stories.tsx

Added best practice guidelines for three button variations: filled, outlined and text.

Update Button Guidelines.stories.tsx

---

Source/DesignSystem/atoms/ConfirmDialog/ConfirmDialog.stories.tsx

Added guidelines to the dialog component including styling, transitions, interaction and types.

Added guidelines to dialog component

---

Source/SelfService/Web/App.tsx

Small change to force build to be re-run

Change file to trigger build

---

Source/SelfService/Web/microservice/microserviceDetails/configurationFilesSection/filesSection/filesSection.tsx

Trying to fix configuration files fetch error that appear after opening microservice.
- Configuration files fetch error

Remove 'try/catch' from filesSection

---

Source/DesignSystem/atoms/AlertBox/AlertBox.stories.tsx
Source/DesignSystem/atoms/AlertBox/AlertBox.tsx
Source/DesignSystem/atoms/Button/Button.stories.tsx
Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/atoms/ConfirmDialog/ConfirmDialog.stories.tsx
Source/DesignSystem/atoms/Forms/Checkbox.stories.tsx
Source/DesignSystem/atoms/Forms/Checkbox.tsx
Source/DesignSystem/atoms/Forms/Form.tsx
Source/DesignSystem/atoms/Forms/Input.tsx
Source/DesignSystem/atoms/Forms/Select.stories.tsx
Source/DesignSystem/atoms/Forms/Select.tsx
Source/DesignSystem/atoms/Forms/Switch.stories.tsx
Source/DesignSystem/atoms/Forms/Switch.tsx
Source/DesignSystem/atoms/Forms/helpers.ts
Source/DesignSystem/atoms/Forms/index.ts
Source/DesignSystem/atoms/IconButton/IconButton.tsx
Source/DesignSystem/atoms/Link/Link.stories.tsx
Source/DesignSystem/atoms/Link/Link.tsx
Source/DesignSystem/atoms/LoadingSpinner/LoadingSpinner.stories.tsx
Source/DesignSystem/atoms/Tabs/Tabs.stories.tsx
Source/DesignSystem/atoms/Tabs/Tabs.tsx
Source/DesignSystem/atoms/Tooltip/Tooltip.stories.tsx
Source/DesignSystem/atoms/Tooltip/Tooltip.tsx
Source/SelfService/Web/microservice/microserviceDetails/configurationFilesSection/filesSection/filesSection.tsx

Added and improved JsDocs in Design System.
Cleaned a code little bit.
- JsDocs to Storybook components
- Combined imports from same place into one line
- Tabs styling as it was outdated

Fixes for storybook

---

Source/DesignSystem/atoms/Button/Button.stories.tsx
Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/atoms/ConfirmDialog/ConfirmDialog.tsx
Source/DesignSystem/atoms/Snackbar/Snackbar.stories.tsx
Source/DesignSystem/index.ts
Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/application/building.tsx
Source/SelfService/Web/application/create/actionButtons.tsx
Source/SelfService/Web/logging/logFilter/activeFilters.tsx
Source/SelfService/Web/logging/logFilter/filterSelect.tsx
Source/SelfService/Web/logging/logLine.tsx
Source/SelfService/Web/microservice/components/card.tsx
Source/SelfService/Web/microservice/components/form/headArguments.tsx
Source/SelfService/Web/microservice/deployMicroservice/deployMicroservice.tsx
Source/SelfService/Web/microservice/microserviceDetails/configurationFilesSection/environmentVariableSection.tsx
Source/SelfService/Web/screens/applicationsScreen/applicationsScreen.tsx

Improved Button component. Added documentation and controls to Storybook so it would be clear how to use them.
- 'subtle' color for cases where button does not need attention.
- Controls for Button.stories
- Link functionality
- 'danger' variant from Button
- Unnecessary Button from filterSelect.tsx

Fix buttons

---

Source/SelfService/Web/api/api.ts

update latest runtime version to 8.9.0

Update latest runtime version to 8.9.0

---

Source/SelfService/Web/api/api.ts

- Update latest selectable runtime version to 8.9.1

Update latest runtime to 8.9.1

---

Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx
Source/SelfService/Web/logging/logFilter/filterSelect.tsx
Source/SelfService/Web/microservice/components/microserviceStatus.tsx
Source/SelfService/Web/microservice/microserviceDetails/microserviceDetails.tsx

Used new Design System Button component to display correct styles on Microservice statuses.
- FilterSelect.tsx style
- MicroserviceStatus.tsx style

More buttons

---

.devcontainer/devcontainer.json
.vscode/settings.json
Source/SelfService/Web/documentation/verifyKubernetesAccess.tsx

- add kubelogin to documentation
Add a section on kubelogin to the verify kubernetes access -documentation

add kubelogin to documentation

---

Source/DesignSystem/atoms/AlertBox/AlertBox.stories.tsx
Source/DesignSystem/atoms/AlertBox/AlertBox.tsx
Source/DesignSystem/atoms/AlertBox/helpers.tsx
Source/DesignSystem/atoms/AlertBox/index.ts
Source/DesignSystem/atoms/AlertDialog/AlertDialog.stories.tsx
Source/DesignSystem/atoms/AlertDialog/AlertDialog.tsx
Source/DesignSystem/atoms/AlertDialog/helpers.ts
Source/DesignSystem/atoms/Button/Button.stories.tsx
Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/atoms/Button/helpers.ts
Source/DesignSystem/atoms/Forms/Checkbox.stories.tsx
Source/DesignSystem/atoms/Forms/Checkbox.tsx
Source/DesignSystem/atoms/Forms/Form.tsx
Source/DesignSystem/atoms/Forms/Input.stories.tsx
Source/DesignSystem/atoms/Forms/Input.tsx
Source/DesignSystem/atoms/Forms/Select.stories.tsx
Source/DesignSystem/atoms/Forms/Select.tsx
Source/DesignSystem/atoms/Forms/Switch.stories.tsx
Source/DesignSystem/atoms/Forms/Switch.tsx
Source/DesignSystem/atoms/Forms/helpers.ts
Source/DesignSystem/atoms/IconButton/Icons.tsx
Source/DesignSystem/atoms/Link/Link.stories.tsx
Source/DesignSystem/atoms/Link/Link.tsx
Source/DesignSystem/atoms/Link/index.ts
Source/DesignSystem/atoms/Tooltip/Tooltip.stories.tsx
Source/DesignSystem/atoms/Tooltip/Tooltip.tsx
Source/DesignSystem/index.ts
Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/application/create/create.tsx
Source/SelfService/Web/microservice/helpers/regex.ts

Overall Design System component improvements. Added documentation with controls to Storybook.
Display The default version of this component, which can also be changed using the controls.
- Missing Stories - Dialog, Select, Switch
- Documentation to Design System
- Design System improvements
- Wrongly used style overrides from Theme

Storybook improvements

---

Documentation/adr/0002-immediate-focus-on-integrations-mvp.md

ADR describing the immediate focus on Bridge / Integrations module

ADR describing the immediate focus on Bridge / Integrations module

---

Source/SelfService/Backend/main.go
Source/SelfService/Backend/main_test.go

Introducing the `SET_HEADERS` environment variable for configuring custom headers for routes. The value of this is expected to be a valid json document, where the keys are the `http.ServeMux` pattern to set headers for, and the value are a json document mapping from http header to [text/template](https://pkg.go.dev/text/template) value (this template is then executed with the incoming request as the data argument). Note: The pattern MUST exactly match a route defined in the `PROXY` environment variable. Also if no `PROXY` is defined, `SET_HEADERS` is ignored.
Example:
```
SET_HEADERS='{"/bridge/": {"X-organisation-id": "{{ .Header.Get \"Tenant-ID\" }}", "Tenant-ID": "..."}}'
```
- `SET_HEADERS` environment variable
- `parseSetHeaders` for parsing the value of `SET_HEADERS`
- functionality …

Introduce SET_HEADERS env var for configuring headers to be set

---

Source/DesignSystem/.storybook/preview.js
Source/DesignSystem/atoms/Accordion/Accordion.tsx
Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/atoms/Forms/Select.tsx
Source/DesignSystem/atoms/Forms/Switch.tsx
Source/DesignSystem/atoms/Icon/Icon.tsx
Source/DesignSystem/atoms/Tabs/Tabs.stories.tsx
Source/DesignSystem/atoms/Tabs/Tabs.tsx
Source/DesignSystem/helpers/ReactRouter.tsx
Source/SelfService/Web/applications/microservice/components/form/headArguments.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/containerImageFields.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/deployMicroservice.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/environmentVariableSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/filesSection/headerButtons.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/containerImageFields.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/headerButtons.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/publicUrlFields.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/setupFields.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/setupSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/healthStatus/healthStatus.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/RouterLinkListItem.tsx

Small code cleanup and made microservices detail view page more mobile friendly.
- Used 'dashedBorder' styles from Design System on inputs
- Disabled buttons going multiple lines
- Styles so pages are looking better on mobile

Overall code improvements

---

Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/apis/solutions/customer.ts
Source/SelfService/Web/applications/backupsScreen.tsx
Source/SelfService/Web/applications/containerRegistryScreen.tsx
Source/SelfService/Web/applications/documentationScreen.tsx
Source/SelfService/Web/applications/logsScreen.tsx
Source/SelfService/Web/applications/m3connectorScreen.tsx
Source/SelfService/Web/applications/microservicesScreen.tsx
Source/SelfService/Web/components/layout/layoutWithSidebar.tsx
Source/SelfService/Web/context/globalContext.tsx
Source/SelfService/Web/index.ejs
Source/SelfService/Web/spaces/applications/applicationsScreen.tsx

Don't show 'change customer' button, if there is only one customer.
- Lang attribute to HTML
- Combine sidebar bottom navigation items with main navigation
- Button line-height from theme
- BackupsScreen list item dot

Change customer btn

---

Source/DesignSystem/atoms/StoryTemplate/StoryTemplate.stories.tsx

added a dummy component template.

Dummy component template

---

Source/DesignSystem/index.ts
Source/DesignSystem/molecules/Stepper/Stepper.stories.tsx
Source/DesignSystem/molecules/Stepper/Stepper.tsx
Source/DesignSystem/molecules/Stepper/index.ts

Add Stepper component to Design System.

Stepper component

---

Source/DesignSystem/atoms/SimpleCard/SimpleCard.stories.tsx
Source/DesignSystem/atoms/SimpleCard/SimpleCard.tsx
Source/DesignSystem/atoms/SimpleCard/index.ts
Source/DesignSystem/index.ts

Added Simple Card component to Design System.

Add card component to Design System

---

Source/DesignSystem/atoms/Forms/Input.stories.tsx
Source/DesignSystem/atoms/Tooltip/Tooltip.stories.tsx
Source/DesignSystem/atoms/Tooltip/Tooltip.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/containerImageFields.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/publicUrlFields.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/setupFields.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/workSpaceLayout.tsx
Source/SelfService/Web/integrations/accordion/components/connectorBundle.tsx
Source/SelfService/Web/integrations/accordion/components/initialSetupForm.tsx
Source/SelfService/Web/integrations/accordion/components/newConnectionAccordion.tsx
Source/SelfService/Web/integrations/accordion/newConnection.tsx

Integration page connection updates

Continue m3 connector

---

Source/DesignSystem/atoms/AccordionList/AccordionList.stories.tsx
Source/DesignSystem/atoms/AccordionList/AccordionList.tsx
Source/DesignSystem/atoms/AccordionList/index.tsx
Source/DesignSystem/index.ts
Source/SelfService/Web/integrations/accordion/components/newConnectionAccordion.tsx
Source/SelfService/Web/integrations/accordion/newConnection.tsx

- Initial test component for Accordion List => needs to be moved to Design System
- Initial implementation of AccordList component
- Create first stories for AccordionList component
- Fix wrong import of componentStories
- Fix typo in comment

accordion list component

---

Source/SelfService/Web/apis/integrations/connectionsApi.hooks.ts
Source/SelfService/Web/integrations/connection/index.tsx
Source/SelfService/Web/integrations/connection/new/components/initialSetupForm.tsx
Source/SelfService/Web/integrations/connection/new/connectionConfigurationReducer.ts
Source/SelfService/Web/integrations/connection/new/index.tsx

- Only show error message when query has error
- Set the staleTime for connectionId query to 1 min
- Populate name and start use of reducer to save value
- Successfully post a name change to the server

connect new setup to backend

---

Source/DesignSystem/atoms/Accordion/Accordion.stories.tsx
Source/DesignSystem/atoms/Accordion/Accordion.tsx
Source/DesignSystem/atoms/StatusIndicator/StatusIndicator.stories.tsx
Source/DesignSystem/atoms/StatusIndicator/StatusIndicator.tsx
Source/DesignSystem/atoms/StatusIndicator/helpers.ts
Source/DesignSystem/atoms/StatusIndicator/index.ts
Source/DesignSystem/atoms/Tooltip/Tooltip.tsx
Source/DesignSystem/index.ts
Source/SelfService/Web/apis/integrations/connectionsApi.hooks.ts
Source/SelfService/Web/integrations/connection/new/components/ConnectorBundleConfiguration.tsx
Source/SelfService/Web/integrations/connection/new/components/MainM3ConnectionInfo.tsx
Source/SelfService/Web/integrations/connection/new/components/MetadataPublisherCredentials.tsx
Source/SelfService/Web/integrations/connection/new/components/TextCopyBox.tsx
Source/SelfService/Web/integrations/connection/new/index.tsx
Source/SelfService/Web/integrations/connections/index.tsx

Add StatusIndicator component to Design System.
- Accordion 'expand' on title click
- StatusIndicator comonent to Design System
- StatusIndicator to Accordtion props
- Minor styling fixes
- Wording/components name fixes

Status indicator comp

---

.dockerignore
Source/SelfService/Web/Dockerfile

Fixing broken build
yarn.lock 
build
- ???

Make sure to copy the yarn.lock file before build

---

Source/DesignSystem/atoms/DataTablePro/helpers.tsx
Source/SelfService/Web/components/noEntityView/noEntityView.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/ContentContainer.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/ContentDivider.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/ContentHeader.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/ContentSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageDetailsSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/SubmitButtonSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSearchResults.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSearchSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/components/MessagesTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/components/NoMessages.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/index.tsx

General code refactoring and wording improvements.

Message details

---

Source/DesignSystem/theming/Icons/Icons.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/exposeData/index.tsx

Added initial Configuration page.

Connection configuration

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/MessagesTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/helpers.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/index.tsx

- Show '-' for dates without deployedAt set or set to minValue
- Add sorting to the mapped message type rows so fields that aren't deployed are at the bottom

fix deployed at

---

Source/SelfService/Web/apis/integrations/messageMappingApi.hooks.ts
Source/SelfService/Web/components/layout/Content/ContentSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/ChangeMessageView.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/MessagesHeader.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/MessagesTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/CopyMessagesButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/DeleteMessagesButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/DeployMessagesButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/TableToolbarButton.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/index.tsx

- Remove local reference to defaultEmptyDate
- Replace Table Header with Content components
- Move Container outside Table component and wire up selected
- Move header section to separate component and pass in selectedIds
- Separate message buttons into separate components
- Show status indictor while copying messages
- Disable other toolbar buttons when an action is executing
- Wire up the DeployButton functionality
- Remove table sorting
- Fix issue where Tablename was not persisted at the Form level
- Disable Delete and Copy to buttons

deploy message type

---

Source/DesignSystem/atoms/Tabs/Tabs.tsx
Source/SelfService/Web/components/layout/page.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/workSpaceLayout.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/exposeData/index.tsx

Fix new workspace layout on smaller screens.
- Page title and status info alignment on smaller screens
- Main layout break in smaller screens
- ExposeData responsivnes

Layout fix

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/MessagesTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/helpers.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/index.tsx

Sort message types list so new appear on top and deployed are sorted ny date

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

- No longer deselect a mapped row automatically
- Update copy based on Figma

Improvements to Table Mapping page

---

Source/SelfService/Web/README.md

Dummy PR just to force a build

---

Source/SelfService/Web/integrations/connection/connectionDetails/exposeData/index.tsx

- Enable deploy service and disable
- Link to live running swagger service

Update expose API for live demo purposes

---

Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/ChangeMessageView.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageDetailsSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/MessagesTable.tsx

Make MessageMappingTable scrollable instead of using pagination.

Messages scroll

---

Source/DesignSystem/atoms/Accordion/Accordion.stories.tsx
Source/DesignSystem/atoms/Accordion/Accordion.tsx
Source/DesignSystem/atoms/AccordionList/AccordionList.tsx
Source/DesignSystem/molecules/FileUploadForm/FileUploadForm.stories.tsx
Source/DesignSystem/molecules/FileUploadForm/FileUploadForm.tsx
Source/SelfService/Web/apis/integrations/connectionsApi.hooks.ts
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/filesSection/filesSection.tsx
Source/SelfService/Web/integrations/connection/configuration/statusResolvers.ts
Source/SelfService/Web/integrations/connection/new/components/IonServiceAccountCredentials.tsx
Source/SelfService/Web/integrations/connection/new/components/M3ConfigurationForm.tsx
Source/SelfService/Web/integrations/connection/new/components/MainM3ConnectionInfo.tsx
Source/SelfService/Web/integrations/connection/new/index.tsx
Source/SelfService/Web/integrations/connection/new/useBuildConfigurationAccordionList.tsx

- Show correct status indicators for each step of wizard
- Add ability to save upload and save ION Configuration 
- [Accordion]: Added `disabled` option to the Accordion
- [FileUploadForm]: Added `clearSelected` to the `fileUploadRef` as a way to programmatically remove the selected files in the form. 
- [FileUploadForm]: Changed the form to be appended to `document.body` so as not to interfere with other active forms.
- [FileUploadForm]: Changed `hideForm` prop to `hideDropArea`

Connector wizard status indicators and storing ion configuration

---

Source/DesignSystem/molecules/DataGrid/DataGrid.stories.tsx
Source/DesignSystem/molecules/DataGrid/DataGrid.tsx
Source/SelfService/Web/applications/backup/backupsDataGrid.tsx
Source/SelfService/Web/applications/backup/backupsListView.tsx
Source/SelfService/Web/applications/backup/listView.tsx
Source/SelfService/Web/applications/backupsScreen.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/setupSection.tsx
Source/SelfService/Web/utils/helpers/regex.ts

This pull request introduces several enhancements and fixes to the Backups page functionality.
- Elevation to DataGrid.
- Backups page DataGrid date column check to ensure the date is valid. Otherwise, it returns 'N/A'
- Loading spinner to Backups page while data is fetching.
- Refactored code.
- Removed the DataGrid wrapper height from 100% as it was causing empty space below the DataGrid.
- Updated Backups DataGrid styles.
- Fixed the issue where the 'Delete Microservice' dialog was closing prematurely.

Backups improvement

---

Source/SelfService/Web/integrations/connection/new/components/ConnectorBundleConfiguration.tsx

Force deploy again

---

Source/DesignSystem/atoms/AlertDialog/AlertDialog.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/ActionToolbar.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/DeleteConnectorDialog.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/exposeData/Credentials/DeleteCredentialDialog.tsx
Source/SelfService/Web/integrations/connections/connectionsTable.tsx

- Delete Connector from within the configuration page
- Remove Delete-functionality from the connection list table

Delete connector with confirmation dialog

---

Source/DesignSystem/molecules/Card/SimpleCardGrid.tsx
Source/SelfService/Web/applications/backup/backupsList.tsx

Fixed SimpleCardGrid breakpoints from sm (small) to md (medium).
- SimpleCardGrid responsive layout grid

Fix SimpleCardGrid breakpoints

---

Source/SelfService/Web/applications/microservice/microserviceDetails/healthStatus/healthStatusTableColumns.tsx
Source/SelfService/Web/applications/microservice/microservices/microservicesTableColumns.tsx
Source/SelfService/Web/utils/helpers/connectionStatuses.ts

Fix rendering of pod status where it can be undefined from the server.

Bugfix: Correctly render pod status when undefined

---

Source/SelfService/Web/integrations/connection/configuration/useBuildConfigurationAccordionList.tsx

- Only show the download bundle section for on premises deployment

Enable M3 configuration for cloud deployment

---

Source/SelfService/Web/integrations/connection/configuration/MetadataPublisherCredentials.tsx
Source/SelfService/Web/integrations/connection/configuration/useBuildConfigurationAccordionList.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/ActionToolbar.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingForm.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/CopyMessagesButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/DeleteMessagesButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/Toolbar/DeployMessagesButton.tsx
Source/SelfService/Web/integrations/connections/connectionsTable.tsx
Source/SelfService/Web/utils/helpers/connectionStatuses.ts
Source/SelfService/Web/utils/helpers/index.ts
Source/SelfService/Web/utils/validation/isValidUrl.ts

- Add URL input validation for the MDP URL field
- Disabled edit/cancel button until the name/deployment type has been saved
- Remove Snackbars with variant: success - it's better to lean on the default grey, which is more consistently used.

Connector configuration improvements

---

Source/SelfService/Web/applications/microservice/deployMicroservice/deployMicroservice.tsx
Source/SelfService/Web/applications/microservice/microserviceViewScreen.tsx
Source/SelfService/Web/applications/microservice/microservices/microservicesDataGrid.tsx
Source/SelfService/Web/applications/microservice/overview.tsx
Source/SelfService/Web/applications/microservicesScreen.tsx

- Use unique id in data grid which leans on microservice id AND environemnt
- Reintroduce enviroment to the url for viewing a microservice

Fix microservice listing and viewing

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

Correctly add mapping for required fields automatically
Show tooltip on hover indicating why Required fields cannot be deselected

Map required fields correctly

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx

Allow native column filtering for Message mapping table

Allow native column filtering for Message mapping table

---

Source/SelfService/Web/components/TextCopyBox.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageFilterSection.tsx

- Support passing text variant to the TextCopyBox
- Improve wording of the message type filters text

Filter wording improvement

---

Source/SelfService/Web/apis/solutions/api.ts

Update link to changelog for 9.0.1

Force deploy runtime version

---

Source/DesignSystem/atoms/LoadingSpinner/LoadingSpinner.tsx
Source/DesignSystem/atoms/LoadingSpinner/index.ts
Source/DesignSystem/index.ts
Source/DesignSystem/templates/Layout/Layout.tsx
Source/SelfService/Web/applications/microservice/components/form/setupFields.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/deployMicroservice.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/configurationFilesSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/environmentSection/environmentVariableSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/filesSection/filesSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/setupSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/healthStatus/healthStatus.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceDetails.tsx
Source/SelfService/Web/applications/microservice/microservices/microservices.tsx
Source/SelfService/Web/applications/microservice/microservices/microservicesDataGridColumns.tsx
Source/SelfService/Web/applications/microservice/overview.tsx

Improved Microservices page appearance.
- FullPageLoadingSpinner to the Design System for waiting to the action complete
- M3Connector option display when deploying the new Microservice
- Layout horizontal scroll

Improve ms pages

---

Source/DesignSystem/templates/Layout/Layout.tsx
Source/SelfService/Web/applications/containerregistry/registryContainer.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceDetails.tsx
Source/SelfService/Web/applications/microservice/microservices/noMicroservices.tsx
Source/SelfService/Web/spaces/applications/applicationsList.tsx
Source/SelfService/Web/spaces/applications/applicationsListItem.tsx
Source/SelfService/Web/spaces/applications/applicationsScreen.tsx

Improve Layout spacing in MicroserviceDetails and ContainerRegsistry page.
Improve NoMicroservises footer text.
Navigate from ApplicationsList to 'building' page when application is not live. (Still needs improvement).

UI improvements

---

Source/SelfService/Web/apis/integrations/CacheKeys.ts
Source/SelfService/Web/apis/integrations/connectionWebhookApi.hooks.ts
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/configuration/ConfigurationContainer.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/realtimeUpdates/ActionToolbar.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/realtimeUpdates/DataSyncConfigurationContainer.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/realtimeUpdates/DisableRealtimeSyncDialog.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/realtimeUpdates/RealtimeSyncSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/realtimeUpdates/RealtimeUpdatesConfigurationContainer.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataRestAPI/EnableRestApiSection.tsx

- Introduce Data Sync Settings section with ability to enable / disable realtime updates
- Rename the Configuration Section to General Settings to play well with the Data Sync settings section

Make it possible to enable / disable realtime data sync

---

Source/SelfService/Web/apis/solutions/api.ts
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/setupSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceDetails.tsx
Source/SelfService/Web/applications/microservice/microservices/microservices.tsx
Source/SelfService/Web/applications/microservice/microservices/microservicesDataGrid.tsx
Source/SelfService/Web/applications/microservice/rawDataLog/view.tsx
Source/SelfService/Web/applications/microservice/utils/getMicroserviceInfo.ts
Source/SelfService/Web/applications/stores/microservice.ts

Fixed API call for 'edit microservice'.
- Updated Microservice types
- Display Microservice info when there is no 'edit' data
- 'editMicroservice' Form submit action

Edit microservice fix

---

Source/DesignSystem/atoms/TextField/TextField.tsx
Source/SelfService/Web/admin/CreateCustomer.tsx
Source/SelfService/Web/admin/index.tsx
Source/SelfService/Web/apis/solutions/customer.ts

Put back CreateCustomer component.

Customer create

---

Source/SelfService/Web/applications/containerregistry/container/registryImages.tsx

Added missing Data Grid row ID-s.

Add ID to DataGrid Row

---

Source/DesignSystem/molecules/DataGrid/DataGridCustomToolbar.tsx
Source/SelfService/Web/applications/containerregistry/container/registryImages/detailPanel/DetailPanelDataGrid.tsx
Source/SelfService/Web/applications/containerregistry/container/registryImages/detailPanel/index.tsx
Source/SelfService/Web/applications/containerregistry/container/registryImages/index.tsx
Source/SelfService/Web/applications/microservice/components/form/containerImageFields.tsx
Source/SelfService/Web/applications/microservice/components/form/headArguments.tsx
Source/SelfService/Web/applications/microservice/components/form/publicUrlFields.tsx
Source/SelfService/Web/applications/microservice/components/form/setupFields.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/configuration/Configurations.tsx
Source/SelfService/Web/utils/helpers/regex.ts

Improved UX and fixed bugs.
- Show current runtime version in Microservice 'configuration' page
- Microservice 'name' input validation rule

Improvements

---

Source/DesignSystem/atoms/AlertBox/AlertBox.tsx
Source/DesignSystem/atoms/Content/ContentContainer.tsx
Source/DesignSystem/molecules/Content/ContentWithSubtitle.tsx
Source/DesignSystem/templates/Layout/Content/ContentHeader.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeData/asyncApi/serviceAccountsSection/index.tsx

Fix 'Consume Data' page crashing when an error occurs.
- Improved AlertBox component wording
- Correct component types specified
- Changed AlertBox title to be a 'p'
- Improved ContentContainer and related components margin and padding

Consume data fix

---

Source/DesignSystem/atoms/AIAssistant/AigonHelperIcon.stories.tsx
Source/DesignSystem/atoms/AIAssistant/AigonHelperIcon.tsx
Source/DesignSystem/atoms/AIAssistant/AigonSearchBar.stories.tsx
Source/DesignSystem/atoms/AIAssistant/AigonSearchBar.tsx
Source/DesignSystem/atoms/AIAssistant/SearchBarWithAigon.tsx
Source/DesignSystem/atoms/AIAssistant/index.ts
Source/DesignSystem/atoms/Forms/Forms.stories.tsx
Source/DesignSystem/index.ts
Source/DesignSystem/molecules/DataGrid/EditCell.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/changeMessage/messageSection/tableSection/MappedTableResult.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/changeMessage/messageSection/tableSection/messageMappingDataGrid/MessageMappingDataGridColumns.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/changeMessage/messageSection/tableSection/messageMappingDataGrid/index.tsx

Add AI-assisted search bar appearance improvements.
- Updated Form.stories appearance and wording in Design System
- Width of MessageMappingDataGrid columns to fill free space
- Component name from AigonHelper to AigonHelperIcon for better readability
- Removed DataGrid EditCell multiline support as it breaks DataGrid scrolling
- Removed AigonSearchBar.stories action when input value was changed as this was breaking the site
- MessageMappingDataGrid pagination code since we don't use it

Ai searchbar improvements

---

Source/DesignSystem/index.ts
Source/DesignSystem/molecules/Content/NoContentView.stories.tsx
Source/DesignSystem/molecules/Content/NoContentView.tsx
Source/DesignSystem/molecules/Content/index.ts
Source/SelfService/Web/integrations/connection/connectionDetails/commands/NoCommandsView.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/CommandsListDataGrid.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/CommandsListDetailPanel.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/CommandsListView.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/getConnectionTabs.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/useRedirectToTabByStatus.tsx
Source/SelfService/Web/integrations/connection/index.tsx
Source/SelfService/Web/integrations/connection/routes.tsx

Add a new 'Commands' tab to the Connection section.
- NoContentView to the Design System

Commands list

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/message/changeMessageView/messageSection/tableSection/MappedTableResult.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/message/changeMessageView/messageSection/tableSection/messageMappingDataGrid/MessageMappingDataGridToolbar.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/message/changeMessageView/messageSection/tableSection/messageMappingDataGrid/index.tsx

Show unselected messages DataGrid rows, when AI search is active.

Ai search improvements

---

Source/SelfService/Web/integrations/connection/connectionDetails/commands/command/CommandSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/commandsListView/commandsListDataGrid/commandsListDetailPanel/DetailPanelColumns.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/commandsListView/commandsListDataGrid/commandsListDetailPanel/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/commands/commandsList/index.tsx

Show dummy data in commands page for now.

Display commands
