dolittle/Studio

.dolittle/Data/resources.json

The Data microservice was missing the resources configuration  so the docker-compose would not run.
So either the resources.json was missing or the docker-compose was not supposed to spin up the runtime for the Data microservice yet.

Add resources configuration to Data under .dolittle so that docker-compose works

---

.github/workflows/deploy-ms.yml

Using the official azure/docker-login action that better handles crazy characters in the password.

Fix build pipline ACR login failure

---

Documentation/k3d.md
Environment/k3d/k8s/mongo.yml

Adds a hardcoded mongo deployment & service to the local dev setup. As Studio doesn't yet dynamically create the required mongodb this is required to get the local dev setup bootstrapped.
Remember to remove sections that you don't need or use.
- New `mongo.yml` to be applied during the bootstrapping phase
- Docs on how to apply it & why we do bootstrapping

Add mongo to the local dev setup

---

Source/SelfService/Web/microservice/purchaseOrder/overview.tsx

Fixes the "COPY TO CLIPBOARD" button in the PurchaseOrderAPI microservice creation view to actually work.
- The "COPY TO CLIPBOARD" button actually works now

Fix the COPY TO CLIPBOARD button to actually work in POAPI creation view

---

.github/workflows/check_labels.yml

Copied the workflow from platform-api to check our PR labels here as well.
- GitHub workflow that checks PR labels to ensure we never forget again

Add release label checker workflow

---

Source/SelfService/Web/App.tsx
Source/SelfService/Web/microservice/purchaseOrder/overview.tsx
Source/SelfService/Web/package.json

Adds a Snackbar when user copies PurchaseOrderAPI URLs to clipboard, with an error if it fails. I found a library that seemed nice https://iamhosseindhv.com/notistack, that simplifies handling multiple snackbars (which is not allowed by Material Design). The library required a bit of hacking with types to get the animation and styling to work, but I think that might be down to something with typescript and dependencies and versions. I think we can clean that up later.
The styling corresponds to the Figma designs for notifications to the best of my ability.
- A global provider to display Snackbars from anywhere easily (notistack)
- Snackbars when copying URLs during the creation of PurchaseOrderAPI

Add snackbar when copying POapi webhook urls.

---

Makefile
Source/SelfService/Web/layout/layoutWithSidebar.tsx
Source/SelfService/Web/microservice/microservice.scss
Source/SelfService/Web/microservice/overview.tsx
Source/SelfService/Web/microservice/viewCard.tsx
Source/SelfService/Web/stores/microservice.ts

Hides the delete button for the raw data log view card
- Start with a clean cluster (or without raw-data-log and purchase-order)
- Click Microservices
- Click Create new microservice
- Click Create within the Purchase order api card
- Select Infor graphic
- Enter name
- Click next
- Enter username
- Enter password
- Click Next
- Click Microservices
- See that there is no delete button on the raw-data-log-v1 webhook microservice 
- canDelete property to microservice view card
- Uses HTML5 hidden to hide delete button from raw data log microservice view card

Hide rawdatalog delete

---

Documentation/k3d.md
Environment/k3d/k8s/persistent-volume.yml
Environment/k3d/k8s/storage-class.yml

Adds a persistent volume and storage class files for the local cluster development. They are called `managed-premium` so as to mock Azure's [`managed-premium`](https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes) storage class that we use. This persistent volume is mounted on k3d cluster creation to `/tmp/k3dvolume`.
This is so that we can have persistence in our local cluster. Related to platform-api PR https://github.com/dolittle/platform-api/pull/36
- `managed-premium` storage class and persistent volume
- Docs on how to apply these during cluster bootstrapping

Add a storage class and persistent volume and docs

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/businessMomentsAdaptor/create.tsx
Source/SelfService/Web/microservice/purchaseOrder/create.tsx

- getLatestRuntimeInfo() returns the latest image and the link to the changelog
- Creating base microservice uses getLatestRuntimeInfo() to get the runtime to use by default.
- Creating purchaseOrderApi microservice uses getLatestRuntimeInfo() to get the runtime to use by default.
- Creating businessMomentsAdaptor microservice uses getLatestRuntimeInfo() to get the runtime to use by default.

Default runtime images 7.1.0

---

Source/SelfService/Web/microservice/overview.tsx

Fixes that only the microservices that belong to the environment are showed in the microservices overview screen.

Fix to only show the environments microservices in the overview

---

Environment/k3d/reset-local-k3d

Makes the `reset-local-k3d` script check that the cluster creation actually worked and that it's in the correct context. This is so that we don't have any accidents in the future again when the context switching fails.

Make the reset-local-k3d script more secure

---

Source/SelfService/Web/api/api.ts
Source/SelfService/Web/microservice/environmentVariables/view.tsx

- Pass in the extact name of the Environment
- On success from the server update original data

Bug fix around environment variable + odd behaviour on saving environment variables a second time

---

Source/SelfService/Web/microservice/base/view.tsx

Fixing a bug when trying to map ingress details to the microservice, ignoring it for now, as the view is not even using the extra.ingress info.

Setting it to empty as it is not used on the view screen

---

Source/SelfService/Web/businessMoments/container.tsx
Source/SelfService/Web/businessMoments/overview.tsx
Source/SelfService/Web/components/pickEnvironment.tsx
Source/SelfService/Web/screens/backupsScreen.tsx
Source/SelfService/Web/screens/businessMomentsScreen.tsx
Source/SelfService/Web/screens/documentationScreen.tsx
Source/SelfService/Web/screens/insightsScreen.tsx
Source/SelfService/Web/screens/microservicesScreen.tsx
Source/SelfService/Web/screens/withRouteApplicationState.tsx
Source/SelfService/Web/utils/route.ts

Opening direct links to microservices in an environment failed sometimes. The cause of this failure is related to which environment the user has last visited. If the user has last been in "Dev", and the link is pointing to "Prod", it would fail. This information is currently stored in local storage.
This PR introduces a higher-order component that reads the `environment` and `applicationId` parameters from the URL, and overwrites these in the global context, which also updates the value in local storage.
- Fix direct links to environments not working when pointing to another environment than the user last visited

Fix direct links with environment not working

---

Source/SelfService/Web/api/index.ts
Source/SelfService/Web/microservice/base/create.tsx
Source/SelfService/Web/microservice/base/view.tsx

Fix microservice creation to default to a public microservice. This is because platform-api v4 has a breaking change where it defaults to private microservice creation if the `isPublic` property on the request is not set (as `bool` types in Go default to `false`).
- https://github.com/dolittle/platform-api/pull/102
- https://github.com/dolittle-platform/Operations/pull/192

Fix microservice creation and request to default to public

---

Source/SelfService/Web/microservice/components/headArguments.tsx

Make the `TextField` for arguments not required.

Make the TextField for arguments not required

---

Source/SelfService/Web/App.tsx
Source/SelfService/Web/api/m3connector.ts
Source/SelfService/Web/layout/layoutWithSidebar.tsx
Source/SelfService/Web/m3connector/container.tsx
Source/SelfService/Web/m3connector/details.tsx
Source/SelfService/Web/m3connector/overview.tsx
Source/SelfService/Web/m3connector/setup.tsx
Source/SelfService/Web/screens/backupsScreen.tsx
Source/SelfService/Web/screens/containerRegistryScreen.tsx
Source/SelfService/Web/screens/documentationScreen.tsx
Source/SelfService/Web/screens/insightsScreen.tsx
Source/SelfService/Web/screens/m3connectorScreen.tsx
Source/SelfService/Web/screens/microservicesScreen.tsx

Add m3connector link on the left to allow the user to interact with the m3 connector setup in the platform
- Able to get an overview of which environment has m3connector setup
- Able to view details about the m3 connector
- Able to trigger setup of the m3 connector (not talking to the backend)
Solves: https://app.asana.com/0/1202121266838773/1202253446321915/f

m3connector experience in Studio - version 1

---

Source/SelfService/Web/logging/lineParsing.ts
Source/SelfService/Web/logging/logFilter/activeFilters.tsx
Source/SelfService/Web/logging/logFilter/dateRangeFilter.tsx
Source/SelfService/Web/logging/logFilter/filterSelect.tsx
Source/SelfService/Web/logging/logFilter/logFilterPanel.tsx
Source/SelfService/Web/logging/logFilter/microserviceFilter.tsx
Source/SelfService/Web/logging/logLine.tsx
Source/SelfService/Web/logging/logLines.tsx
Source/SelfService/Web/logging/logPanel.tsx
Source/SelfService/Web/logging/logPanelAbsolute.tsx
Source/SelfService/Web/logging/logPanelRelative.tsx
Source/SelfService/Web/logging/loki/logLines.ts
Source/SelfService/Web/logging/loki/parsing.ts
Source/SelfService/Web/logging/loki/queries.ts
Source/SelfService/Web/logging/loki/types.ts
Source/SelfService/Web/logging/loki/useLogsFromLast.ts
Source/SelfService/Web/logging/loki/useLogsFromRange.ts
Source/SelfService/Web/package.json
Source/SelfService/Web/screens/logsScreen.tsx
Source/SelfService/Web/theme/buttonText.tsx
Source/SelfService/Web/tsconfig.json
tsconfig.json
yarn.lock

- Change the "Last 24 hours" into -> "Live logs" and enable streaming.
- Move the _selection description_ into the title of the LogPanel.
- Add `Timestamp` switch to the LogPanel, that turns on timestamps for each log line.
- Fix indentation of wrapped lines, the wrapped lines will now be indented the same amount as the leading whitespace of the original line.
- Enable "Date Range" selection to view logs from a absolute range (and implement the code to fetch logs from a range)
- Add the Microservice selection multi select dropdown, and corresponding chips in the filters.
To fix a bug with the math of nanosecond timestamps returned by Loki, I needed to use BigInts - which required an upgrade of the TypeScript target to ES2020. I believe this is OK now, and 90% reported by caniuse.com …

Microservice dropdown, view in absolute date range and timestamps for Logs

---

Source/SelfService/Web/screens/logsScreen.tsx

- Fixes so that the microservice filter dropdown only shows microservices for the current environment

Only show microservices in current env in filter

---

Environment/mock/monitoring/logs/generated.js
Environment/mock/monitoring/logs/index.js
Source/SelfService/Web/logging/logLine.tsx
Source/SelfService/Web/logging/logPanel.tsx
Source/SelfService/Web/logging/loki/useLogsFromLast.ts
Source/SelfService/Web/logging/loki/useLogsFromRange.ts
Source/SelfService/Web/logging/shimmeringLogLines.tsx

Adds shimmering LogLines in a LogPanel that is currently loading more logs. Also fixed the "No logs found" message so that it does not appear while loading logs.
Note: A slightly annoying behaviour is - if you toggle the Timestamp while shimmering lines are shown, the animation is not in sync with the text. But this is kind of edge case, as the loading doesn't really appear for long.
- The `useLogsFromLast` no longer retains the last loaded logs while loading more, this seems more in line with the designed UX with these new shimmering lines.
- A tiny bug in `useLogFromRange` caused it to not update the state to `loading: true` while fetching logs.

Show shimmering lines while fetching log lines

---

Source/SelfService/Web/logging/logPanel.tsx
Source/SelfService/Web/logging/logPanelAbsolute.tsx
Source/SelfService/Web/logging/logPanelRelative.tsx
Source/SelfService/Web/package.json
Source/SelfService/Web/screens/logsScreen.tsx
yarn.lock

Adds "infinite scrolling" to the date-range log view (`LogPanelAbsolute`). This works by adding an empty div to the bottom of the `LogPanel` and when it is scrolled into the viewport, it triggers loading more logs (which only happens if there are more to load).
Currently this will only work on browsers with the `IntersectionObserver` api supported: https://caniuse.com/mdn-api_intersectionobserver. Which I believe is fine. For browsers without the support, no auto-loading will happen.
- `LogPanel` accepts extra content before and after the log-lines with a `header` and `footer` property.
- Some hardcoded values in `LogPanelRelative` and `LogPanelAbsolute` are exposed now with props as defaults.
- `LogPanelAbsolute` now accepts a Ref as a prop that will be set to the `loadMoreLogs` function …

Load more logs with "infinite scrolling" when viewing date-range logs

---

.codeclimate.yml
Source/SelfService/Web/application/create.tsx
Source/SelfService/Web/components/topRightMenu.tsx
Source/SelfService/Web/layout/layoutWithSidebar.tsx
Source/SelfService/Web/microservice/viewCard.tsx

This PR brings a more polished look to Studio by removing "TODOs" from various parts of the application.
- Side menu item objects are now consistently named across the file layoutWithSideBar.tsx
- Removed the `STATUS:TODO` from the Microservice cards
- Removed the snackbar TODO when typing in the contact email in the Create new application flow.
- Removed the bell icon and the three-dot menu from the top right of every page as they were "TODOs" as well.

Remove todos and usermenus

---

Source/SelfService/Web/microservice/base/view.tsx
Source/SelfService/Web/microservice/purchaseOrder/view.tsx

Removed unused 'edit' and 'delete' buttons with them styles.
- Unused 'edit' and 'delete' buttons from deployed microservices page.
- Formatted code since it was quite messy.

Remove nonfuncioning buttons

---

Source/SelfService/Web/.docker/custom-entrypoint.sh
Source/SelfService/Web/.docker/nginx.conf
Source/SelfService/Web/Dockerfile

Fixes an issue we have where navigating back to e.g. `dolittle.studio` after logging out caused a cached version of the frontend to be loaded - which then failed to get any data because the user is not logged in. By changing the server of the SelfService/Web frontend to NGINX, and setting up explicit caching rules - the browsers should now only cache the static files (which webpack invalidates by changing the name) and not any paths leading to the `index.html` file. This means that the frontend will be reloaded on any browser navigation.
- The SelfService/Web server from `gostatic` to `nginx` to allow more control of the serving of content.
- The SPA caching that caused strange behaviour when navigating after logging out, and old versions of the SPA served after new deployments until a …

Configure caching of the SelfService/Web server

---

Source/SelfService/Web/insights/runtimeStatsV1/utils.ts
Source/SelfService/Web/utils/formTextFieldsValidation.ts

'Create new application' form email validation was too lose. I updated the regex to make the check more efficient.
- 'Create new application' form email error sensitivity.

Fix form errors

---

Source/DesignSystem/molecules/Metrics/Graph.stories.tsx
Source/DesignSystem/molecules/Metrics/Graph.tsx
Source/SelfService/Web/microservice/microserviceView/healthStatus/healthStatus.tsx

Adds a `range` and `domain` property on the `Graph` component so that we can make the empty-state look a bit better. The HealthStatus page should now look like this when there is no data:
- `range` and `domain` props to set the extends on a `Graph` component explicitly. By default they are calculated from the data.
- The `HealthStatus` page sets the domain to be the last 24 hours - and sensible ranges for CPU and Memory.

Domain and range for graph

---

Source/SelfService/Web/App.tsx
Source/SelfService/Web/utils/useViewportResize.ts

The `Vega` graph components use the `window:resize` event to re-calculate their own size. However, it turns out that this event **is not triggered** when a scrollbar is shown or hidden. This lead to some graphs having the wrong size if more content was loaded later and making the scrollbar appear.
This little fix listens to the `window.visualViewport:resize` event, which **is triggered** when a scrollbar is shown or hidden, and re-dispatches a new `window:resize` event. This forces `Vega` graphs to recalculate as normal, and it shouldn't cause issues for other elements.
- The `Vega` graphs did not re-calculate their size when a scrollbar appeared, which meant that for small windows the `CPU Usage` graph would be a little too wide when the `Memory Usage` graph appeared.

Fix Graph size calculation bug caused by scrollbar appearing.

---

Environment/mock/api/applications/index.js
Source/SelfService/Web/microservice/delete.tsx
Source/SelfService/Web/microservice/microserviceView/microserviceView.tsx
Source/SelfService/Web/microservice/purchaseOrder/view.tsx
Source/SelfService/Web/microservice/rawDataLog/view.tsx
Source/SelfService/Web/microservice/view.tsx

Fixes a bug where switching environments on the `MicroserviceView` (and other) screens causes a blank page to be a shown. Turns out it was not filtering microservices from the `MicroserviceStore` correctly - which caused it to partially load data for the wrong microservice. This is definitely not a good fix - but solves the problem for now.
- The Mock-server now behaves more like the actual production APIs
- Getting Microservice-data from the store did not filter on environment, causing redirects to the overview not happening.

Fix bug where Environment selector on MicroserviceView screen shows a blank screen

---

Source/SelfService/Web/api/api.ts

Update the runtime dropdown selection to display the latest version `8.6.0` when creating a microservice.

Update latest runtime to 8.6.0

---

Source/SelfService/Web/api/application.ts
Source/SelfService/Web/screens/applicationsScreen/applicationsScreen.tsx

When logging in to studio and there are no applications in the tenant you were logged in for you'd get a black screen. Now instead you will get an empty list and the choice to create a new application or go back to choose another tenant.
- Bug when no applications existed in the tenant
Before fix:
After Fix:

Bug-applications-list

---

Source/Bridge/bridge-frontend/next.config.js

No longer proxy requests to `/api` in production, and trust the ingress will kick in when it is set up

Modify /api rewrites to only be active for development

---

Source/DesignSystem/.storybook/main.js
Source/DesignSystem/.storybook/manager.js
Source/DesignSystem/.storybook/preview.js
Source/DesignSystem/atoms/Button/Button.stories.tsx
Source/DesignSystem/atoms/Button/Button.tsx
Source/DesignSystem/atoms/ConfirmDialog/ConfirmDialog.tsx
Source/DesignSystem/atoms/DataTablePro/DataTablePro.stories.tsx
Source/DesignSystem/atoms/LoadingSpinner/LoadingSpinner.stories.tsx
Source/DesignSystem/atoms/Snackbar/Snackbar.stories.tsx
Source/DesignSystem/package.json
Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/application/create/create.tsx
Source/SelfService/Web/logging/logFilter/activeFilters.tsx
Source/SelfService/Web/logging/logLine.tsx
Source/SelfService/Web/microservice/components/headArguments.tsx
Source/SelfService/Web/microservice/create/card.tsx
Source/SelfService/Web/microservice/microservice.tsx
Source/SelfService/Web/microservice/microserviceStatus.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/emptyDataTable.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/environmentVariablesSection/environmentVariableSection.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/filesSection/buttonGroup.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/filesSection/filesSection.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/setupSection/setupSection.tsx
Source/SelfService/Web/microservice/microserviceView/healthStatus/healthStatus.tsx
Source/SelfService/Web/microservice/noMicroservices.tsx
Source/SelfService/Web/screens/adminScreen.tsx
Source/SelfService/Web/screens/applicationsScreen/actionButtons.tsx
Source/SelfService/Web/screens/applicationsScreen/applicationsScreen.tsx
yarn.lock

Add Dark theme to the Storybook as it fits better with Studio.
Added jsDocs for Button component.
Created custom button variant 'danger' for cases where the primary action is destructive such as deleting content.
Created cutom button variant 'fullwidth' that makes button as wide, as its container. Used mostly in Data Table Grids when there is no rows yet.
- Dark theme to Storybook. Components didn't had good contrast with white background.
- Custom button variants: 'danger' and 'fullwith'.
- Secondary color variant to button.
- Button default variant to 'text'.
- Renamed button that adds new environment variable file.
- Renamed button that takes back to tenant.
- Actions on the Storybook Canvas. This is still to be discussed but removed for a better user experience.

Big buttons organizing

---

Source/DesignSystem/atoms/Button/Button.tsx
Source/SelfService/Web/logging/logLine.tsx

To fix the problem with the Dashlane browser extension, I added component='span' and role='none' to the Button component.
Otherwise, Dashlane wanted to interact with the regular button component and significantly slowed down the 'live logs' page.
- Component props to Button.
- Role props to Button.

Add span component and role='none' to button

---

.github/workflows/deploy-selfservice-web.yml
Source/SelfService/Web/App.tsx

The build step "Push Semantic Image to Docker Hub" was missing the build-args attribute so this was never passed into the dockerisation, and thus the license key was never set.
- deployment step for semantic version to include build-args
- made small change to self-service to force deployment

Fix deployment buildargs

---

Source/DesignSystem/atoms/AlertBox/AlertBox.stories.tsx
Source/DesignSystem/atoms/AlertBox/AlertBox.tsx
Source/DesignSystem/atoms/AlertBox/index.ts
Source/DesignSystem/index.ts
Source/SelfService/Web/App.tsx
Source/SelfService/Web/application/building.tsx
Source/SelfService/Web/application/create/create.tsx
Source/SelfService/Web/logging/logPanel.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/environmentVariablesSection/environmentVariableSection.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/filesSection/filesSection.tsx
Source/SelfService/Web/microservice/microserviceView/configurationFilesSection/restartInfoBox.tsx
Source/SelfService/Web/microservice/microserviceView/healthStatus/healthStatus.tsx

Make AlertBox component in Design System reusable and add JsDocs for documentation.
Display AlertBox in stories and added controls so it would be easier to understand how to use alerts in code.
- JsDocs to AlertBox.tsx
- Controls to AlertBox.stories.tsx
- Controlled alert 'open' and 'close' state if needed
- Better wording in alertBox.stories.tsx
- How to use links inside alert message

Alert box fixes

---

Source/SelfService/Web/api/api.ts

this puts new services on the at-this-time latest runtime version
change the "8" version of the runtime to 8.8.2, which is currently the latest
not 100% sure that nothing else needs to change - so a review would be nice :)

change runtime version 8 to 8.8.2

---

Source/SelfService/Web/api/api.ts

Use v6.2.4 as the latest v6 of the runtime.

Support latest v6 runtime (6.2.4)

---

Source/SelfService/Web/containerregistry/images.tsx

As part of the upgrade to latest react router (#301) the image/tags route was changed and no longer supported using `/` as part of the URL. This fix encodes the :image parameter so that it should work
- Fix broken links to images tags in container registry view for images containing '/'

Fix broken links to images tags in container registry view for images containing '/'

---

Makefile
Source/SelfService/Backend/go.mod
Source/SelfService/Backend/main.go
Source/SelfService/Backend/main_test.go

To enable requests to be routed to different backend services, this PR introduces proxy configuration via the `PROXY` environment variable. This is needed for e.g. routing bridge related requests to the bridge-api, and platform related request to the platform-api. Also some rudimentary tests are added.
Configurable routing via the optional `PROXY` environment variable. The value of this variable, if present, is assumed to be a valid json document where the keys are a [http.ServeMux](https://pkg.go.dev/net/http#ServeMux) pattern and the values are the corresponding host for the backend to setup a reverse proxy to. 
If no `PROXY` environment variable is given, or if it's value is empty, we'll fallback to the old behavior of using the `PLATFORM_API` environment variable.
The `PLATFORM_API` …

Add routing to backend

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSearchSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/index.tsx

- Presist the search state when going back to search results
- Not show '0' when there are no search results

back to search results

---

Source/SelfService/Web/apis/integrations/messageMappingApi.hooks.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageDetailsSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/SubmitButtonSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/index.tsx

- Successfully map the fiieldName changes from table into state
- clean up the code and remove some logging
- Use form context to set the selected fields in form
- Use form context's isValid to disable save button
- Mark row as selected when value has been mapped
- Wire up the mutation to save a new message type
- Add success and error handling with navigation and snackbars

save message mapping

---

Source/DesignSystem/atoms/Forms/Form.tsx
Source/DesignSystem/atoms/Forms/index.ts
Source/DesignSystem/index.ts
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingForm.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

- Extend Form with a ref that returns the hook methods
- Use secondary option by passing in ref as props without forwardRef
- Set the form values after request has returned data

Fix broken new message type form by setting initial state after data has loaded

---

Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

- Generate unique fieldname when mass-selecting a table
- Optimize the unique creation slightly by not needing to create a new Set for each loop

Fix unique naming when mass-selecting table

---

Source/SelfService/Web/applications/microservice/deployMicroservice/containerImageFields.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/setupSection/containerImageFields.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageDetailsSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingForm.tsx
Source/SelfService/Web/spaces/applications/create/inputField.tsx
Source/SelfService/Web/utils/validation/patterns.ts

- Update current alpha numeric regex pattern to include it's for lower case only
- Use any cased alpha numeric regex for input validation of message type name
- Trigger form validation after initial values have been set

Improve message type name validation to not support non alpha numeric characters

---

Source/SelfService/Web/applications/backup/backupsListItems.tsx

BackupsListItems displayed only limited hardcoded environment values. If the value was not listed, 'N/A' was displayed.
- Removed fixed environment values from BackupsListItems.

Fix BackupsListItems environment display

---

Source/DesignSystem/atoms/Forms/Input.tsx
Source/DesignSystem/atoms/Forms/PasswordInput.stories.tsx
Source/DesignSystem/atoms/Forms/PasswordInput.tsx
Source/DesignSystem/atoms/Forms/index.ts
Source/DesignSystem/theming/Icons/Icons.tsx
Source/SelfService/Web/integrations/connection/new/components/ActionButtons.tsx
Source/SelfService/Web/integrations/connection/new/components/M3ConfigurationForm.tsx
Source/SelfService/Web/integrations/connection/new/components/MainM3ConnectionInfo.tsx
Source/SelfService/Web/integrations/connection/new/components/MetadataPublisherCredentials.tsx
Source/SelfService/Web/integrations/connection/new/index.tsx
Source/SelfService/Web/integrations/connection/new/useBuildConfigurationAccordionList.tsx

Improvements to the new connector page that supports better validation and flow of the form
- PasswordInput: Add PasswordInput component with show/hide password functionality
- New Connector:  Validation and enabling save button when configuring new connector
- Enable save button when there are changes and valid
- Reset fields after successfully saving
- Make connector name and deployment type required
- Required metadata password/url to be required if one of them is set
- Enable "Start Message Mapping" button when conneciton is Connected
- New Connector: Expand configuration sections when user has selected deployment typw
- Input: Extend Input to accept "type" as a string prop that defaults to text

Validation Rules for new connector page

---

Source/SelfService/Web/integrations/connection/configuration/M3ConfigurationForm.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/ActionToolbar.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/new/index.tsx

- Reset form state after succesful submit
- Reset Form back to original values when pressing "Cancel"
- More straight forward saving of form and cleaned up ActionToolbar

Reset M3 configuration form state correctly

---

Source/SelfService/Web/integrations/connection/connectionDetails/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/useRedirectToTabByStatus.tsx
Source/SelfService/Web/integrations/connection/index.tsx
Source/SelfService/Web/integrations/connections/connectionsTable.tsx
Source/SelfService/Web/integrations/connections/index.tsx

- WIP: Todos
- Redirect to correct tab when loading connection screen
- Extract redirect to logic into hook
- Slight improvement to the active tab resolving logic - would be good to make this part of the tab component though, maybe a RouterTabs?

Redirect to connector tab by connection status

---

Source/SelfService/Web/integrations/connection/connectionDetails/useRedirectToTabByStatus.tsx

Actually fix redirect logic to evaluate the subpath exists, not that it ends with the route

Fix broken redirect to messages sub paths (again)

---

Source/SelfService/Web/integrations/connection/configuration/ConnectorBundleConfiguration.tsx
Source/SelfService/Web/integrations/connection/configuration/IonServiceAccountCredentials.tsx
Source/SelfService/Web/integrations/connection/configuration/TextCopyBox.tsx

- Make TextCopyBox a reusable component
- Wrap instructions for IonServiceCredentials in a CopyBox

Wrap IonServiceCredentials instructions in copy box

---

Source/DesignSystem/atoms/Forms/Select.tsx
Source/SelfService/Web/App.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/createSpaceDialog.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/spaceCreateDialog.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/spaceSelectMenu.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/workSpaceLayout.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/workSpaceLayoutLinks.tsx
Source/SelfService/Web/home/homeScreen.tsx
Source/SelfService/Web/home/homeScreenCardGridItems.tsx
Source/SelfService/Web/integrations/connection/configuration/MainM3ConnectionInfo.tsx
Source/SelfService/Web/integrations/connection/configuration/MetadataPublisherCredentials.tsx
Source/SelfService/Web/integrations/connections/index.tsx
Source/SelfService/Web/integrations/index.tsx

Few fixes and code refactoring for new layout.
- Auto focus on SpaceCreateDialog input field
- Required 'pageTitle' prop to WorkSpaceLayout
- Replaced HomeScreen 'Dolittle' text with 'Aigonix'
- Renamed CreateSpaceDialog to SpaceCreateDialog
- Added WorkSpaceLayoutWithSidePanel and changed naming on them
- Select new space after creating it
- Comment out the 'Breadcrumbs' as they are not working correctly at the moment
- SidePanel 'ErpConnections' link path so it would take to main Integrations page
- Connections Form errors from required prop
- Variant 'success' from Integrations Snackbar

New nav fixes

---

Source/SelfService/Web/components/layout/layoutWithSidebar.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/workSpaceLayoutLinks.tsx

Made links clearer to improve UX.
- LayoutWithSidebar 'Documentation' link label to 'Setup'
- WorkSpaceLayout SelectMenu 'Documentation' Link href to open 'https://dolittle.io/docs/' in new tab

Improve wording

---

Source/SelfService/Web/apis/integrations/CacheKeys.ts
Source/SelfService/Web/apis/integrations/kafkaServiceAccountApi.hooks.ts
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/serviceAccounts/GenerateServiceAccountForm.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/serviceAccounts/GenerateServiceAccountFormSubmitButton.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/serviceAccounts/ServiceAccountsSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/serviceAccounts/ServiceAccountsTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataRestAPI/Credentials/CredentialsContainer.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSearchSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/index.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/messagesList/index.tsx
Source/SelfService/Web/integrations/connection/index.tsx
Source/SelfService/Web/integrations/connection/new/index.tsx
Source/SelfService/Web/integrations/routes.hooks.ts

- Ability to create Kafka Service Accounts from the Consume Data (Event Streams) page for a connection
- Listing out of existing Kafka Service Accounts
- UX details
- Hide Generate button from header when form is visible
- Show the ISODate time on hover over the created at column for a service account

Create and list out kafka service accounts for event streams

---

Source/DesignSystem/theming/theme.ts
Source/SelfService/Web/App.tsx
Source/SelfService/Web/components/layout/landingPageDesider.tsx
Source/SelfService/Web/components/layout/layoutWithSidebar.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/spaceSelectMenu.tsx
Source/SelfService/Web/components/spaceCreateDialog.tsx
Source/SelfService/Web/spaces/applications/applicationsList.tsx
Source/SelfService/Web/spaces/applications/applicationsListItem.tsx
Source/SelfService/Web/spaces/applications/applicationsScreen.tsx

Improved log in pages appearance.
Create new applications in a Dialog, not on a separate page.
If the user has only one application, navigate directly to the Microservices page, otherwise navigate to the Applications page.
- LandingPageDesider that navigates to the starting page
- ApplicationsScreen 'create new application' appearance
- Style fixes
- Add currentApplicationId to store if navigated directly to Home page and application is not selected yet

Application selection

---

Source/SelfService/Web/App.tsx
Source/SelfService/Web/components/layout/landingPageDecider.tsx
Source/SelfService/Web/components/layout/landingPageDesider.tsx
Source/SelfService/Web/components/layout/workSpaceLayout/spaceSelectMenu.tsx

Fix LandingPageDecider errors.
- Rename create new 'Space' to 'application' in NavigationBar
- Get current application ID from GlobalContext
- Typo in 'LandingPageDecider'

Application select fixes

---

Source/SelfService/Web/integrations/connection/connectionDetails/consumeDataEventStreams/index.tsx

Add Certificate Authority file for a user to download from the Consume Event Streams tab

Add Certificate Authority download link for Kafka

---

Source/SelfService/Web/apis/solutions/containerregistry.ts
Source/SelfService/Web/applications/containerregistry/container.tsx
Source/SelfService/Web/applications/containerregistry/tags.tsx
Source/SelfService/Web/applications/microservice/deployMicroservice/deployMicroservice.tsx

This changes the tag list to use the new image-tags endpoint in platform-api, to get a list of
tags (sorted by creation date), with additional meta data.
It also adds linking between the tags list and the create microservice
screen, where it prefills the head image field with the value found in
the URI fragment identifier.
- Mechanism for adding prefilled image name to the head image field in the create new microservice screen
- New metadata to the tags list
- Links from the tags list to the create new microservice screen
- The tags api to use the `image-tags` endpoint instead of `tags`
- The tags list
- The create new microservice screen (to be able to get an optional image name from the URI fragment identifier for the head image field)

Improve the container registry image tags list

---

Source/DesignSystem/atoms/Forms/Forms.stories.tsx
Source/DesignSystem/atoms/Forms/Select.tsx
Source/SelfService/Web/integrations/connection/configuration/MainM3ConnectionInfo.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/configuration/ActionToolbar.tsx

- Fix: Save button did not enable after selecting the deployment type and name. The issue was with the Select component not firing the validation rules.
- Form: Create a Form.story for easier testing and future documentation of Forms
- Select: Fix bug where validation rules were not fired for Select changes.
- Select: Improve validation evaluation for Select to happen onChange, even when form is onTouched
- Sleect: Add validation error messages to the Select component

Fix name and deployment triggering save for new connector

---

Source/DesignSystem/helpers/DummyContents/DummyNavigationItems.tsx
Source/DesignSystem/molecules/SidePanel/SidePanel.tsx
Source/DesignSystem/templates/Layout/Layout.tsx
Source/SelfService/Web/admin/adminScreen.tsx
Source/SelfService/Web/applications/backup/backupsList.tsx
Source/SelfService/Web/applications/backup/backupsListItems.tsx
Source/SelfService/Web/applications/backupsScreen.tsx
Source/SelfService/Web/applications/containerRegistryScreen.tsx
Source/SelfService/Web/applications/containerregistry/registryContainer.tsx
Source/SelfService/Web/applications/documentationScreen.tsx
Source/SelfService/Web/applications/logsScreen.tsx
Source/SelfService/Web/applications/m3connectorScreen.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/configurationFilesSection/environmentSection/environmentVariableSection.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceDetails.tsx
Source/SelfService/Web/applications/microservice/microservices/microservices.tsx
Source/SelfService/Web/applications/microservicesScreen.tsx
Source/SelfService/Web/applications/setup/setupContainerScreen.tsx
Source/SelfService/Web/components/layout/breadcrumbs.tsx
Source/SelfService/Web/components/layout/page.tsx
Source/SelfService/Web/components/layout/workSpaceLayout.tsx
Source/SelfService/Web/components/layout/workSpaceLayoutLinks.tsx
Source/SelfService/Web/context/globalContext.tsx
Source/SelfService/Web/home/homeScreen.tsx
Source/SelfService/Web/integrations/index.tsx
Source/SelfService/Web/utils/helpers/connectionStatuses.ts

Replaced Layout with new WorkSpaceLayout.
- Current environment to GlobalContext to be used at the moment in Backups page.
- 'Div' around MicroserviceDetails so content is not in Flex Container.
- 'selected' prop to SidePanel navigation that shows active panel.
- A temporary spacing on the Integrations page that takes 'breadcrumbs' place.
- Error handling in pages, when data is not found. Removed navigation to a 'problem' page.
- Link to Setup page in new layout.
- Style improvements for new layout.
- Link to Backups list view.
- Breadcrumbs as they were not consistant and useful.

Add new layout

---

Source/SelfService/Web/applications/logging/logLine.tsx

Fixed log line text that overflowed if long text has no spaces.

Add 'word-break' styles to LogLine text

---

Source/DesignSystem/atoms/TextField/TextField.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/MessageMappingTable.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

- Add support for quick filtering of the table fields
- Move responsibility of filtering selected to the grid itself to trigger item count correctly

Quick filter fields in message mapping table

---

Source/DesignSystem/atoms/Forms/Switch.stories.tsx
Source/DesignSystem/atoms/Switch/Switch.stories.tsx
Source/DesignSystem/atoms/Switch/Switch.tsx
Source/SelfService/Web/integrations/connection/connectionDetails/messages/changeMessage/components/TableSection.tsx

- Fix wrongly inverted boolean being passed into the switch to hide unselected rows in the message mapping table
- [DesignSystem]/NewSwitch] - Fix 'NewSwitch" and pass the props to the component - alternatively, we should pass in only 'checked.'

Fix switch to hide unselected rows in the message mapping table

---

Source/SelfService/Web/apis/solutions/api.ts
Source/SelfService/Web/applications/logging/index.tsx
Source/SelfService/Web/applications/microservice/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/configuration/Configurations.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/configuration/configurationFiles/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/configuration/environmentVariable/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/configuration/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/healthStatus/index.tsx
Source/SelfService/Web/applications/microservice/microserviceDetails/microserviceView/index.tsx
Source/SelfService/Web/applications/microservice/microservicesOverview/microservicesList/MicroservicesList.tsx
Source/SelfService/Web/applications/microservice/microservicesOverview/microservicesList/microservicesDataGrid.tsx
Source/SelfService/Web/applications/microservice/utils/getMicroserviceInfo.ts
Source/SelfService/Web/applications/stores/microservice.ts

Changed microservices to use the new endpoints which include pod status when listing services. This means each service does not need to individually call getpodstatus, and can render faster.
The new endpoint also uses the images which are actually used by the running pod, which means there will no longer be a stale runtime version.

Switched service listings to use new endpoint with pod status included

---

Source/DesignSystem/atoms/Tabs/Tabs.tsx

Take Tabs render method outside of its 'tabs' wrapper. This will fix layout issues.
- Marked 'tabs' wrapper as a 'nav' component

Render tabs content outside of the tabs wrapper
